---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kinda.rocks
  resources:
  - snapshotstrategies
  - storestrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kinda.rocks
  resources:
  - snapshotstrategies/finalizers
  - storestrategies/finalizers
  verbs:
  - update
- apiGroups:
  - kinda.rocks
  resources:
  - snapshotstrategies/status
  - storestrategies/status
  verbs:
  - get
  - patch
  - update
