# permissions for end users to edit storestrategies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: storestrategy-editor-role
rules:
- apiGroups:
  - kinda.rocks
  resources:
  - storestrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kinda.rocks
  resources:
  - storestrategies/status
  verbs:
  - get
